# Generated by Django 3.2.11 on 2022-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_books', to='bookclub.Book'),
        ),
    ]
