# Generated by Django 3.2.5 on 2022-02-18 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='bookclub.book'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chooser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
