# Generated by Django 3.2.11 on 2022-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='bookclub.Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
