# Generated by Django 3.2.5 on 2022-02-11 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(null=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
