# Generated by Django 3.2.11 on 2022-02-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_club_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='is_private',
            new_name='club_type',
        ),
    ]
