# Generated by Django 3.2.5 on 2022-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_chat_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
    ]
