# Generated by Django 3.2.11 on 2022-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=18000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
