# Generated by Django 3.2.11 on 2022-03-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_auto_20220218_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_icon',
            field=models.CharField(default='3.png', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookclub.club'),
        ),
    ]
