# Generated by Django 3.2.11 on 2022-02-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
