# Generated by Django 3.2.11 on 2022-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
