# Generated by Django 3.2.11 on 2022-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_user_all_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='all_books',
            field=models.ManyToManyField(blank=True, related_name='_bookclub_user_all_books_+', to='bookclub.Book'),
        ),
    ]
