# Generated by Django 3.2.5 on 2022-03-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chat',
        ),
    ]
