# Generated by Django 3.2.11 on 2022-02-12 21:41

import _queue
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_rename_is_private_club_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicants',
            field=models.ManyToManyField(default=_queue.Empty, related_name='clubs_applied_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
