# Generated by Django 3.2.5 on 2022-03-13 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_rename_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='bookclub.club'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
