# Generated by Django 3.2.11 on 2022-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_auto_20220302_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_icon',
            field=models.CharField(default='static/images/2.png', max_length=10),
        ),
    ]
