# Generated by Django 3.2.11 on 2022-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_auto_20220407_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=1530),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=260),
        ),
    ]
