# Generated by Django 3.2.11 on 2022-02-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_auto_20220201_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=250),
        ),
    ]
