# Generated by Django 3.2.11 on 2022-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_auto_20220407_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
