# Generated by Django 3.2.11 on 2022-02-12 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_club_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='applicants',
            field=models.ManyToManyField(related_name='clubs_applied_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
