# Generated by Django 3.2.11 on 2022-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_alter_club_club_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_icon',
            field=models.CharField(default='/images/3.png', max_length=10),
        ),
    ]
