# Generated by Django 3.2.11 on 2022-02-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_title'),
        ('bookclub', '0004_alter_rating_review'),
    ]

    operations = [
    ]
