# Generated by Django 3.2.11 on 2022-02-01 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_merge_0002_alter_book_title_0004_alter_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
