# Generated by Django 3.2.11 on 2022-02-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_alter_club_applicants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
    ]
