# Generated by Django 3.2.11 on 2022-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_auto_20220310_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
