# Generated by Django 3.2.11 on 2022-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_book_pages_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, default='https://i.imgur.com/f6LoJwT.jpg'),
        ),
    ]
