# Generated by Django 3.2.11 on 2022-02-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_auto_20220206_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(max_length=1000)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='bookclub.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='bookclub.club')),
            ],
        ),
    ]
